version: "3"

services:
  compute-engine:
    image: gcr.io/f1-telemetry-app/compute-engine
    command: launch.py
    ports:
      - 5000:5000
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud
    tty: true